### ISSUE TITLE
(Feature Request) Custom Toolbar Icons

### ISSUE THREAD

**Issue by stackingflow** [Figma-Linux/figma-linux-themes#4]
Please add an option to change/theme the toolbar icons (example: move tool, pen tool etc) by pasting svg code or uploading svg.

**Comment by ChugunovRoman** [comment]
@stackingflow this is hard to implement this, because the figma does not provide any API (not REST api I mean methods for communicate with ElectronJS) for changing toolbar icons.
And even if I implement this functionality, it will most likely work incorrect, and in the future it may stop working altogether.
